version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fortuna
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: fortuna:latest
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
