version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    image: fortuna:latest
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db