export const JokeTypes = {
    LEFT_GAME: 1,
    TAG_REGISTERED: 2,
    START_GAME: 3,
    DEACTIVE_GAME: 4,
    ADD_GUEST: 5,
    SAY_SOMETHING_TO_INACTIVE: 6,
    DELETE_PLAYER: 7,
    TAG_UNDECIDED: 8
}