export enum JokeTypes {
    TAG_REGISTERED = 'TAG_REGISTERED',
    TAG_GAMERS = 'TAG_GAMERS',
    TAG_UNDECIDED = 'TAG_UNDECIDED',
    ADD_GUEST = 'ADD_GUEST',
    CHANGE_LIMIT = 'CHANGE_LIMIT',
    DELETE_PLAYER = 'DELETE_PLAYER',
    SAY_SOMETHING_TO_INACTIVE = 'SAY_SOMETHING_TO_INACTIVE'
} 