name: Deploy to Server on Kamatera

on:
  push:
    branches:
      - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug secret
              run: |
                echo "FORTUNE_KAMATERA is set: ${{ secrets.FORTUNE_KAMATERA != '' }}"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.FORTUNE_KAMATERA }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ghcr.io/kamran134/fortuna-telegram-bot:latest

            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                known_hosts: unnecessary

            - name: Add Known Hosts
              run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            - name: Test SSH Connection
              run: ssh -vvv -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo SSH connection successful"

            - name: Deploy to Kamatera Server
              run: |
                    ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
                        echo "${{ secrets.FORTUNE_KAMATERA }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                        docker-compose up web -d
                        docker system prune -f -a
                    EOF